### PR TITLE
Lucashh/22 build features

### PR DESCRIPTION
**Pull request by lucashuet93**
- adds features released at Build
  - adds new simple-round-robin-v2 API that utilizes load balancing infrastructure
  - adds new weighted-round-robin-v2 API that utilizes load balancing infrastructure
  - adds new retry-with-payg-v2 API that utilizes load balancing and circuit breaker infrastructure
  - updates rate-limiting API to utilize `<azure-openai-token-limit />` policy
  - updates usage-tracking API to utilize `<azure-openai-emit-token-metric />` policy
- adds e2e tests for the v2 APIs
- updates docs

The usage-tracking e2e test still needs to display the token metrics, but I elected to leave that for #5.

### CODE REVIEW

**Comment by stuartleeks** [comment]
@lucashuet93 I tried deploying this but got `Cannot create API 'aoai-api-rate-limiting' with the same Path 'rate-limiting/openai' as API 'aoai-api-rate-limting'  unless it's a part of the same version set`. Is there a clash with previous versions?

**Comment by stuartleeks** [comment]
@lucashuet93 can you also add README files for the v2 capabilities?

**Comment by lucashuet93** [comment]
@stuartleeks you may need to freshly redeploy so it doesn't conflict with existing APIs already deployed to APIM. I will add READMEs for them but thought I might do so in a separate docs related PR. Can add here.

**Comment by lucashuet93** [comment]
@stuartleeks I added the docs for the new capabilities and updated the existing ones. Ready for re-review.

**Comment by stuartleeks** [comment]
> @stuartleeks I fixed a typo in the rate limting APIs path so now it needs to be freshly redeployed or you'll get the above error.

Is it worth adding a troubleshooting section to the main README? That would give us somewhere that we can include notes like this

**Comment by lucashuet93** [comment]
> > @stuartleeks I fixed a typo in the rate limting APIs path so now it needs to be freshly redeployed or you'll get the above error.
> 
> Is it worth adding a troubleshooting section to the main README? That would give us somewhere that we can include notes like this

Good idea, added!

**Review by stuartleeks — APPROVED** [review]
LGTM!

**Pull request merged**
